# Generated by Django 4.1.4 on 2023-01-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(auto_created=True, max_length=200, unique=True),
        ),
    ]
